apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bank.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bank.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bank.labels" . | nindent 6 }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge }}
  template:
    metadata:
      labels:
        {{- include "bank.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.deployment.template.specNginx.name }}
          image: {{ .Values.deployment.template.specNginx.image }}
          ports:
            - containerPort: {{ .Values.deployment.template.specNginx.ports.containerPort }}
              name: {{ .Values.deployment.template.specNginx.ports.name }}
              protocol: {{ .Values.deployment.template.specNginx.ports.protocol }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              scheme: HTTP
              path: /api/v1/bank/health_check
              port: 80 
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              scheme: HTTP
              path: /api/v1/bank/health_check
              port: 80  
        - name: {{ include "bank.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              scheme: HTTP
              path: /api/v1/bank/health_check
              port: 5000  
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              scheme: HTTP
              path: /api/v1/bank/health_check
              port: 5000            
          env:
          - name: {{ .Values.envVariables.dbEnv.name }}
            value: {{ .Values.envVariables.dbEnv.dbname }}
          - name: {{ .Values.envVariables.userEnv.name }}
            valueFrom:
              secretKeyRef:
                key: {{ .Values.envVariables.userEnv.secret_key }}
                name: {{ .Values.envVariables.userEnv.secret_name }}
          - name: {{ .Values.envVariables.passEnv.name }}
            valueFrom:
              secretKeyRef:
                key: {{ .Values.envVariables.passEnv.secret_key }}
                name: {{ .Values.envVariables.passEnv.secret_name }}
          - name: {{ .Values.envVariables.hostEnv.name }}
            value: {{ .Values.envVariables.hostEnv.host }}
      volumes:
        - configMap:
            name: {{ include "bank.name" . }}-nginx-config
          name: nginx-config